[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Robert Usher <266585+dcchut@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rprompt = "2.0"
anyhow = "1.0"
rayon = "1.7"
crossbeam = "0.8"
num = "0.4"
ordered-float = "3.5"
pathfinding = "4.2"